### ISSUE TITLE
BasicScore and TextField for Kiwi.HUD.Widget do not have default color.

### ISSUE THREAD

**Issue by zacharyf1991** [gamelab/kiwi.js#153]
I can understand TextField not having default style but I assumed that the score widget would have a built in style. Or at least a default color.

**Comment by BenjaminHarding** [comment]
Looked into adding a default to the TextField and ScoreWidgets but decided not to. 

The reason is that if we do assign a default color then any external selector that users could set wouldn't be (easily) settable due to [selector specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity). 

Also currently it will inherit the default color of its parent, which is probably fine in most cases as it would most likely be black. (The example repo is unique case where the default color `white` matches the default background color of the document). 

On another line of thought, I do think that users being able to set default styles upon creation of the widget should be explored though and will keep this in-mind for future.
