### ISSUE TITLE
Kiwi.Geom.Intersect.LineToRawSegment working incorrectly.

### ISSUE THREAD

**Issue by zacharyf1991** [gamelab/kiwi.js#166]
LineToRawSegment algorithm is incorrect. Will always return the true when the rawSegment is a verticle line. How this occurs:

When using Kiwi.Geom.Intersect.lineToRectangle ( or  ( ray || lineSegment )ToRectangle ) the intersect result will always be true. 

From my investigation I have identified the the problem occurs ( either first or only on ) where the left hand side of the rectangle calculation is being done on the Kiwi.Geom.Intersect.lineToRectangle function. 

The left hand side of the box is correctly being identified so the problem is with the line intersect algorithm itself.

**Comment by zacharyf1991** [comment]
You can see an example of this not working is in the example repo. It will not be displayed on the main page but the files will be visible inside of the 'geom' folder. To enable them you can do this from the kwi-example-main.js file inside of the 'kiwi-examples/examples/_site/js/' folder. See line 43.

**Comment by BenjaminDRichards** [comment]
Intersect fixes include:
* `lineToRawSegment` now requires both X and Y coordinates of intersection to be within segment span.
* New `lineSegmentToRawSegment()` method (technically an API expansion, but necessary for these fixes).
* `lineSegmentToCircle` now checks for intersection success rather than intersect object (which might not have succeeded) in worst case scenario.
* `lineSegmentToRectangle` now uses `lineSegmentToRawSegment()` for better results, and returns an intersect point equal to the centroid of the line if the line is entirely within the rectangle.

Line fixes include:
* Can now deal with points on (0,0), and accelerates vertical lines.

This ensures that several intersection methods now operate more robustly and as predicted.

A more robust check of all the Geom.Intersects methods, using horizontal and vertical lines, may be called for.
