### ISSUE TITLE
Mouse.cursor.preventDown etc doesn't seem to work

### ISSUE THREAD

**Issue by BenjaminDRichards** [gamelab/kiwi.js#191]
I have `preventDown=true`, the default state. When I click the right mouse button, the default context menu appears. This seems like it shouldn't happen.

**Comment by BenjaminHarding** [comment]
After investigating this issue preventDown does work and is actually set to true by default. I think this issue was just miscommunication, since it doesn't control the context menu. 

Being able to disable the context menu would still be desired behaviour and so we should add this functionality to Kiwi soon!

**Comment by BenjaminHarding** [comment]
Functionality has been added to the Mouse Class around the context menu.

```
 //Disable the context menu from appear.
 //Off by default to maintain functionality with older versions of Kiwi
 this.game.input.mouse.preventContextMenu = true;

 //Add methods to be executed when the context menu should appear.
 this.game.input.mouse.onContext.add(function() {
  alert('Context menu event fired!');
 }, this);
```

Above functionality will only work on Kiwi.JS versions 1.3.0 or above
