### ISSUE TITLE
Camera:Transform Point method

### ISSUE THREAD

**Issue by BenjaminHarding** [gamelab/kiwi.js#201]
The transform point method on the Camera Class doesn't return correct values every second time it is called. This can produce odd results in dev version 1.3.1 of Kiwi.

**Comment by BenjaminDRichards** [comment]
Problem solved.

`Camera.transformPoint` was reported to return wrong values every second time it was called. This turns out to be due to the new matrix caching code in `Transform`. In older versions, `getConcatenatedMatrix` would always create a new matrix from scratch, so several methods would get a concatenated matrix and then append to it raw. In newer versions this will pollute the cached concatenated matrix.

I've adjusted `Camera.transformPoint`, `Camera.transformPointToScreen`, `Box._rotateRect`, and `Box._rotateHitbox` to copy the concatenated matrix into a scratch matrix. This seems to prevent pollution.
