### ISSUE TITLE
TextField leaks dom nodes

### ISSUE THREAD

**Issue by UncleZeiv** [gamelab/kiwi.js#218]
I need to use a multitude of short lived text fields. This seems to be leaking JS nodes according to Chrome's debugger.

I had a look at the code, and indeed `TextField` doesn't seem to have a `destroy()` method. It does create a bunch of resources, among which there's a `document.createElement("canvas");`. The canvas is then added to `this.state.textureLibrary` via a `SingleImage` object and never removed from there.

To reproduce, just create a state like the following:
```javascript
var MainState = new Kiwi.State("MainState");

MainState.create = function () {
  MainState.sprite = new Kiwi.GameObjects.TextField(MainState, "X");
}

MainState.update = function () {
  MainState.sprite.destroy();
  MainState.sprite = new Kiwi.GameObjects.TextField(MainState, "X");
}
```
and keep an eye on Chrome's debugger.

**Comment by BenjaminHarding** [comment]
Thanks @UncleZeiv for the thorough investigation! Will try to fix it for the next release.

Also if you are using lots of short lived textfields then reusing them instead of creating fresh textfields should also help with performance :)

**Comment by UncleZeiv** [comment]
Hi @BenjaminHarding, thanks for your reply. Just checking... was this closed on purpose? It was added to the milestone and then closed immediately.

**Comment by BenjaminHarding** [comment]
Woops! Thanks again @UncleZeiv. Must have pressed the wrong button :S

**Comment by BenjaminHarding** [comment]
Source of the problem was that indeed that more Dynamic Textures (such as those created via Textfields) would be created, used, but then never removed. 

To combat this we added a `remove` method to the TextureLibrary for removing unused TextureAtlases. 

This investigation also has shown us the `GLTextureManager` only cleared its cache when you switched states. So additional methods have been added and used to help with Texture Management. 

**Another Note**
Took me a little too long to figure it out, but the example above isn't completely valid in the current version of Kiwi (<=1.4.0). 

This is a bit complicated but it's because the destroy method currently requires that a boolean be passed indicating whether or not to execute immediately, or after at the next update. And since the gameobject isn't attached to the State, it will never be removed. 

To fix this the destroy method now checks to see if it gameobject resides in the scene graph or not, and if it doesn't then it will set immediately to true, and execute the destroy functionality.
