### ISSUE TITLE
File Loading not working correctly

### ISSUE THREAD

**Issue by zacharyf1991** [gamelab/kiwi.js#66]
Pointed this out to Mr.Harding when I found that the loadProgress() method of the state did not return the 'bytesLoaded' 

Please make sure file loading is working correctly.

**Comment by BenjaminHarding** [comment]
In the previous version of Kiwi you had to set the 'calculateBytes' flag on the loader to 'true' in order to get the number of bytesLoaded. This is because if files are being loaded via tag loading methods, the size of the files are cannot be received. 

This functionality still exists in 1.2, but it now also attempt to also give an estimate number of bytesLoaded even if you did not set the 'calulateBytes' flag to true. Just a warning that it will not be accurate as any file loaded not using XHR will not be taken into account.
